simple-pipeline:
  trigger:
    include:
      - local: cicd/simple-pipeline.yml

gtest-pipeline:
  trigger:
    include:
      - local: cicd/gtest-pipeline.yml

post:
  script:
    - echo "All pipelines Executed successfully"
  needs:
    - simple-pipeline
    - gtest-pipeline
